/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SubmarinoScreen */

#ifndef _Included_SubmarinoScreen
#define _Included_SubmarinoScreen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SubmarinoScreen
 * Method:    keyListner
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SubmarinoScreen_keyListner
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
